### ISSUE TITLE
Class Diagram

### ISSUE THREAD

**Issue by aishairzay** [baehre/CollaborativeMusicPlayer#6]
Think about the classes into which you will implement your project and draw them into its design
class diagram. Make sure you include all the details that we described in class, such as: type
information, accessibility, visibility, attributes, and methods. Write a brief text explaining which classes
of your class diagram belong to which components of your architecture diagram from Assignment 2.

**Comment by ajdimarco** [comment]
Finished User class diagram

**Comment by ajdimarco** [comment]
Hurry up Andrew

**Comment by baehre** [comment]
I did it. Some of us had multiple to do.
